### ISSUE TITLE
How can view organizations and styles Tab in keycloak Admin console

### ISSUE THREAD

**Issue by syama-aot** [p2-inc/keycloak-orgs#100]
I tried to compile keycloak-orgs package and got Jar file. Once i place the keycloak-orgs-0.36-SNAPSHOT.jar file in providers folder (keycloak 21.1.1) .I was able to access the organization API and created organization. Everything works smoothly. But I am unable to have  organization tab in keycloak admin console. I tried to set the themes ( But i could not get phaseTwo theme) . Can you guide me in this regard .

**Comment by xgp** [comment]
The organization admin UI has to be built from our fork of the Keycloak admin UI. 

https://github.com/p2-inc/keycloak

I would recommend instead using our docker images, which already contains everything. 

https://quay.io/repository/phasetwo/phasetwo-keycloak?tab=tags

**Comment by syama-aot** [comment]
If I want to customize keycloak-orgs (attribute mapper format) , How can I
change and upload again in that docker container? Can you provide me with a
small example.

Thanks

**Comment by xgp** [comment]
You can either take a look at how the image gets built here:

https://github.com/p2-inc/phasetwo-containers

or just use our image as a base image and replace the jar in your Dockerfile.

**Comment by syama-aot** [comment]
Thanks, I'll check it out.  I have one more question. I want to use the new
role created in one organization in all other organizations also. Can you
guide me on that

**Comment by xgp** [comment]
Not currently possible, but will be in the future. See https://github.com/p2-inc/keycloak-orgs/issues/48

**Comment by syama-aot** [comment]
Ok, thanks for the reply. At Least is it possible to add new* default
roles. That way we can get all default roles to all organizations right.
Can you guide me on this direction*

**Comment by xgp** [comment]
That’s done in code here https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/resource/OrganizationAdminAuth.java#L159

**Comment by syama-aot** [comment]
I added 2 roles productA-admin, orgA-admin . But it's not reflecting .
Which are the places  I need to update (which files) . Please guide me.
Thanks

**Comment by xgp** [comment]
When you add to that array, the additional roles are added to the org when the org is created. 

For additional step-by-step guides, please post comprehensive information about exactly what you are doing and what you expect. I’m not able to provide personalized support here.

**Comment by xgp** [comment]
They are isolated. Please see the README.

**Comment by syama-aot** [comment]
Thank you for the clarification. Is it possible to change defined role as
default role.

**Comment by xgp** [comment]
No.
