### ISSUE TITLE
where to get the keycloak admin jar

### ISSUE THREAD

**Issue by jaayb** [p2-inc/keycloak-orgs#101]
Relatively new to keycloak and I'm trying to implement your keycloak-orgs extension.  I was able to follow the instructions to generate the jar.  I'm trying to get the keycloak-admin-client jar but not sure how to go about that.  Any advice?  Not a Java developer.  Tried creating a pom file and generating the jar that way with maven but when I add both of these to the provider directory and restart nothing is showing up in the master realm.

**Comment by xgp** [comment]
Building this yourself can be challenging if you are not familiar with Java and Maven. I would recommend using the Docker images to get started https://quay.io/repository/phasetwo/phasetwo-keycloak?tab=tags

**Comment by jaayb** [comment]
I tried spinning up the docker containers but couldn't browse to the admin interface.  Already have keycloak up and running so I was trying to go that route.

**Comment by xgp** [comment]
You need to select the ‘phasetwo.v2’ admin theme in Realm Settings->Themes and then log out/in to get the custom theme.

**Comment by SNJnet** [comment]
i have all jar's in the provider folder but the phasetwo theme isnt showing in the admin console. Do i need to put it elsewhere?

**Comment by xgp** [comment]
Can you please show me the layout of your `providers/` folder? The `phasetwo-admin-ui-21.1.1.0.jar` must be there. If you have further problems, I suggest using the contents of the docker image as a guide.

**Comment by SNJnet** [comment]
![Unbenannt](https://github.com/p2-inc/keycloak-orgs/assets/138109939/8e31511e-d9f4-4738-ad18-67b5b370817e)
The Keycloak is run without docker so that is not an option.

**Comment by xgp** [comment]
You need the `phasetwo-admin-ui-21.1.1.0.jar`

I'm not suggesting you need to use docker. I'm suggesting you look at our docker image to understand which jars need to be in the providers dir.

**Comment by jaayb** [comment]
> You need the `phasetwo-admin-ui-21.1.1.0.jar`
> 
> I'm not suggesting you need to use docker. I'm suggesting you look at our docker image to understand which jars need to be in the providers dir.

Thanks for the Idea.  I copied all the jars from the docker container's providers folder and deployed in my installation.
