### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by SNJnet** [p2-inc/keycloak-orgs#104]
Hi i downloaded your code and saw that an Method that is used isnt defined anymore.
Its in IdpSelectorAuthenticator.java Line 42 getIdentityProviderbyAlias().
![Unbenannt](https://github.com/p2-inc/keycloak-orgs/assets/138109939/c2dd194f-fa32-4f6d-9350-4d535d08088e)

Hope you can fix that.

**Comment by xgp** [comment]
Not sure if there is some version conflict in your IDE, but that method is there:
https://www.keycloak.org/docs-api/21.1.2/javadocs/org/keycloak/models/RealmModel.html#getIdentityProviderByAlias(java.lang.String)
