### ISSUE TITLE
Link to Portal

### ISSUE THREAD

**Issue by SNJnet** [p2-inc/keycloak-orgs#106]
Hi when i use the link  for the Portal with and without /auth/ i get the client not found page of keycloak do i need to activate the portal?

**Comment by xgp** [comment]
The IdP wizards are not available as open source.

**Comment by SNJnet** [comment]
is that also the case for the api? when i try a api call for the orgs i get a 404 error.

**Comment by xgp** [comment]
The org APIs are part of this extension and are open source. Please post the details of your request so I can see how you are getting a 404.
