### ISSUE TITLE
Update tests to use Testcontainers

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-orgs#108]
The `KeycloakServer` in testsuite doesn't get released, and makes it hard for other people to run these tests. It's also clear that it has diverged from running a "real" Keycloak server, so we are potentially missing some things in our tests.

We should port to use dasniko's keycloak `testcontainers`. We did the port in `keycloak-themes` already, so we should be able to use it as a model https://github.com/p2-inc/keycloak-themes/pull/12

**Comment by xgp** [comment]
This somewhat complicated by the fact that `OrganizationProviderTest` needs a `KeycloakSession` directly. I don't have a great idea of how to maintain those tests without `KeycloakServer`.
- Keep a separate profile (and separate test dir, because of compilation problems) for the tests that still require `KeycloakServer`.
- Delete those tests, and just make sure they are implicitly tested through `OrganizationResourceTest`.

**Comment by xgp** [comment]
https://github.com/p2-inc/keycloak-orgs/pull/120

**Comment by ngaxavi** [comment]
I can help to write tests using Testcontainers

**Comment by xgp** [comment]
Thanks @ngaxavi

I’ve got a branch with a start on this that I’ll push tonight.

**Comment by xgp** [comment]
@ngaxavi Branch https://github.com/p2-inc/keycloak-orgs/tree/xgp/testcontainers

**Comment by ngaxavi** [comment]
@xgp can you give access to this branch so that I push my changes.

**Comment by xgp** [comment]
@ngaxavi Just fork off that branch and open a new PR.

**Comment by xgp** [comment]
Fixed by #130
