### ISSUE TITLE
Organization search does not recognize the organization name first character

### ISSUE THREAD

**Issue by AustinOyugi** [p2-inc/keycloak-orgs#109]
When calling the

` /orgs?q=name:{orgname}`
 
  being handled by `listOrgs` under `OrganizationsResource`
  
  The criteria builder uses
  
 ` builder.like(root.get("name"), "%" + value.toLowerCase() + "%")`
  
  Which takes in a lowercase value without converting the `root.get("name")` to a `builder.lower` expression

**Comment by AustinOyugi** [comment]
Requesting to be assigned the issue...

**Comment by AustinOyugi** [comment]
review the pull request: https://github.com/p2-inc/keycloak-orgs/pull/110

**Comment by xgp** [comment]
Fixed in #116 

Thanks to @AustinOyugi for the original issue and PR.
