### ISSUE TITLE
Keycloak 19.0.1 extension issue

### ISSUE THREAD

**Issue by Vorimo** [p2-inc/keycloak-orgs#11]
Hi! I'm using Docker with quay.io/keycloak/keycloak:19.0.1 image and also PostgreSQL 14 as a database.
Here's my Dockerfile:

`FROM quay.io/keycloak/keycloak:19.0.1
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=******
COPY ./built-extensions/ /opt/keycloak/providers/
CMD ["build"]
CMD ["-v start-dev --storage=jpa --db-url=jdbc:postgresql://***:5432/<my_db> --db-username=*** --db-password=***"]`

I'm trying to check how this extension works.

**Expected behavior:**
Changelog information appears in logs and in the database -> new realm resources added

**Actual behavior:**
I don't see any information about executed scripts in the Keycloak logs, also seems like nothing changed inside the db itself (no records inside changelog table). But by some lines of logs I can approve that the extension deployed and at least something works:
INFO  [io.phasetwo.service.resource.OrganizationResourceProviderFactory] (main) OrganizationResourceProviderFactory::initRoles

Seems like the process stuck somewhere in between, and unfortunately I can't debug all the way since I don't know about the proper way of it's working. Am I missing something?

I would be very thankful if someone will help me with that issue, thanks in advance!

**Comment by xgp** [comment]
Hi @Vorimo. We're working on better examples in the documentation. I'll add more information in https://github.com/p2-inc/keycloak-orgs/issues/10 as we add it.
