### ISSUE TITLE
Organization mapper: displayName support

### ISSUE THREAD

**Issue by mweibel** [p2-inc/keycloak-orgs#117]
I was wondering if we could find a way to expose the displayName in the mappers, additionally to the name. I know I could just send a PR to add it but I was wondering whether there's a way to make it a flag so people can decide what to expose?
Otherwise I guess it would make sense to make a separate mapper which exposes the displayName instead of the name?

**Comment by xgp** [comment]
Sure @mweibel . The [mappers](https://github.com/p2-inc/keycloak-orgs/tree/main/src/main/java/io/phasetwo/service/protocol/oidc/mappers) can have configuration exposed with `ProviderConfigProperty`. You could add a bool config option for including the display name, and then update the `getOrganizationClaim` method to optionally include it in the claim. 

Alternately, we created a `/me` endpoint a while back as an alternative to using claim mappers. The idea is similar to the OIDC `/userinfo` endpoint, but to give you an easy way to get all of the information about the logged-in user's organizations:
- https://phasetwo.io/api/get-me
- https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/resource/OrganizationsResource.java#L47

**Comment by xgp** [comment]
@mweibel If you choose to update or do a new mapper, I'll keep this issue open to track. Otherwise, please close.

**Comment by mweibel** [comment]
thank you for the information! I'll have a look a bit later - the /me endpoint sounds interesting too but I couldn yet try it.

**Comment by mweibel** [comment]
actually, I just tested it quickly and `/me` is fine 👍 thanks!
