### ISSUE TITLE
Please respect MIT license of Home IdP Discovery extension

### ISSUE THREAD

**Issue by sventorben** [p2-inc/keycloak-orgs#118]
Hello!

You recently mentioned me as the author (and copyright holder) of the [Home IdP Discovery](https://github.com/sventorben/keycloak-home-idp-discovery/blob/main/LICENSE.md) extension in #83.
This made me curious to understand what you are using my extension for. While looking at your repository, I noticed that you have copied a lot of my code in the package `io.phasetwo.service.auth.idp` (see https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/idp/).

As you know and acknowledged in [package-info.java](https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/idp/package-info.java) this code is distributed under [MIT license](https://github.com/sventorben/keycloak-home-idp-discovery/blob/main/LICENSE.md). 

The license requires that the copyright notice and the permission notice shall be included in all copies or substantial portions of the Software. 

May I kindly ask you to adhere to the license and add both.

Thanks
Sven-Torben

**Comment by xgp** [comment]
Hi @sventorben Thanks for the message. The intent of the `package-info.java` was to include the copyright and permission notice, so I apologize if it doesn't meet the standard of the license. Can you help me understand exactly what would be required to meet the license standard? Copyright and license notice on every source file?

**Comment by sventorben** [comment]
Hey @xgp,

thanks for the quick response.

I did not include the license in every file, because I find that somewhat annoying.

You will need a "physical" copy of the license and copright notice. So, simple add the [license file](https://github.com/sventorben/keycloak-home-idp-discovery/blob/main/LICENSE.md) in the package and keep the copyright notice in there.
