### ISSUE TITLE
404 Not Found when opening IDP Wizard

### ISSUE THREAD

**Issue by DamienTehDemon** [p2-inc/keycloak-orgs#126]
Did not see a template anywhere, if there is one please link it and I will update or recreate the issue.

I am running into a problem where I am getting a 404 error when I click the setup sso button on the org portal.

https://test.domain.co/realms/Development/wizard/?org_id=e1d84542-37ce-404d-9b63-ea92e35c60e2

I have a realm created with the name Development. My application automatically makes the organization. I then manually added a user, and added that user to the org, and assigned him roles.

Does the URL look correct? Is there something I am missing in the configuration? I did not add anything to start using this other then using the P2-INC image.

**Comment by xgp** [comment]
The IdP wizard is closed source and only available in the cloud version or to licensees.

**Comment by DamienTehDemon** [comment]
Where can I find information about the licensing?

**Comment by xgp** [comment]
https://phasetwo.io 

***@***.***
