### ISSUE TITLE
Login selecting Organizations

### ISSUE THREAD

**Issue by mrp4sten** [p2-inc/keycloak-orgs#127]
This not an Issue but. I want to try make a simple Login that have a Authentication Flow with the follow Steps:

- Username Form
- Organization Form (For example)

The behavior that I want is that we can login to a Any Application using the Username and Selecting one Organizations from a Select by example.
I can do this? How can I do? If you can answer this questions please add images to undertand better

**Comment by xgp** [comment]
@mrp4sten thanks for your message. In this extension, there really is not a concept of "selecting" an organization. You can associate one or more organizations with a user, and then map those organization memberships into the token or userinfo. It is up to your application to "select" an organization.
