### ISSUE TITLE
organization theme

### ISSUE THREAD

**Issue by AbrorxonAloxonov** [p2-inc/keycloak-orgs#131]
I want to enter additional information when opening an organization. but I could that is, I want to enter the id when opening Organization. id is currently being generated.not find the code related to create organization in the projects. please help me to change the create organization theme.

**Comment by AbrorxonAloxonov** [comment]
![image](https://github.com/p2-inc/keycloak-orgs/assets/109734441/3eeca8a7-8f7b-4f1e-aafe-4c742ce8bd60)

**Comment by xgp** [comment]
The ID is generated when an organization is created. This is not something that can be changed.

**Comment by AbrorxonAloxonov** [comment]
> The ID is generated when an organization is created. This is not something that can be changed.

I want to save a unique organization inn number issued by the state. can you please help me where i can find the code of "craet an organization" theme shown in the picture

**Comment by AbrorxonAloxonov** [comment]
or can I add a separate column without changing the id?

**Comment by xgp** [comment]
It's not possible using this extension.

**Comment by xgp** [comment]
There are Organization attributes, which are arbitrary key/values. You could set an attribute for the value you want to store.

**Comment by AbrorxonAloxonov** [comment]
> It's not possible using this extension.

Why can't I add a new field?

**Comment by AbrorxonAloxonov** [comment]
I saw all the jar file codes in the docker image, I think these codes are incomplete, that is, not all of them are shown?

**Comment by xgp** [comment]
> Why can't I add a new field?

You can do whatever you want. I just can't add those to this extension or help you, as it's outside of the scope of what this library does.

> I saw all the jar file codes in the docker image, I think these codes are incomplete, that is, not all of them are shown?

Sorry. I'm having extraordinary difficulty understanding your questions. I don't think I can help you with this project.

**Comment by AbrorxonAloxonov** [comment]
> ![image](https://user-images.githubusercontent.com/109734441/272385268-3eeca8a7-8f7b-4f1e-aafe-4c742ce8bd60.png)

I apologize if my questions were unclear. my last question. which project's ui code in this picture is in which js file.
