### ISSUE TITLE
Configuration Validation Fails in "Upload Google IdP information" Step in SSO Wizard Page

### ISSUE THREAD

**Issue by diazoxide** [p2-inc/keycloak-orgs#133]
## Current Behavior:
When navigating to the SSO Wizard page and attempting to validate Google IdP meta file using the "Validate Meta File" button, the validation fails. The button response displays "Configuration validation failed with Google SAML IdP. Check file and try again."
<img width="1499" alt="image" src="https://github.com/p2-inc/keycloak-orgs/assets/25997814/0b9a6d42-7e04-457d-8720-63053fb16595">

## Console Logs:
In the console, there's a 404 error when trying to send a request to an undefined endpoint: https://usw2.auth.ac/auth/realms/taza/orgs/SET_ORG_ID/idps/import-config
<img width="755" alt="image" src="https://github.com/p2-inc/keycloak-orgs/assets/25997814/a06d1ed6-6555-43dd-bd5f-050673850f2a">

## Expected Behavior:
Validation should succeed, and there should be a meaningful error message if it fails, guiding the user to resolve the issue.

## Steps to Reproduce:

Navigate to SSO Wizard page
Proceed to the "Upload Google IdP information" step
Click on the "Validate Meta File" button

**Comment by xgp** [comment]
@diazoxide This is a known bug. The shared clusters are not yet updated to the most recent version of the wizards that fixes this. I'll update the ticket once we roll out the new version.

**Comment by xgp** [comment]
Within the next week.

**Comment by xgp** [comment]
This is updated. Post if you see the problem on the new versions.
