### ISSUE TITLE
Team entity in keycloak-orgs

### ISSUE THREAD

**Issue by hookenful** [p2-inc/keycloak-orgs#14]
Hello there!

I see there is an entity "Team" in source code of keycloak-orgs. Is that planning feature? I don't see any things for it around here. 
I am asking, because there is need to introduce some "projects" functionality and I noticed that "team" definition is close to that.

I've noticed comment for "teams are on hold for now". 
Is there a reason for that?

**Comment by hookenful** [comment]
If it possible, I can elaborate to help with that functionality, but honestly I am fulltime C# developer with zero Java experience, but can adapt with some help of workspace setup and debug setup.

What I've already done:
- Installed IntelliJ IDEA
- Cloned keycloak repository with success build
 ```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:12 min
[INFO] Finished at: 2022-09-27T10:06:10+03:00
[INFO] ------------------------------------------------------------------------

```
Which help I need:
- Setup for debug keycloak SPI in IDEA. Is it possible?

**Comment by xgp** [comment]
We've decided to hold off on teams for a while, as there has been no pull from customers. 

I don't know how to set up Keycloak debugging in IntelliJ. I know there have been a few postings on the Keycloak boards, but I can't find them right now.

**Comment by xgp** [comment]
Closing for now. Please reopen if you decide to add the functionality.

**Comment by hookenful** [comment]
Are there any notices about what have already been done for teams and what needs to be done?

**Comment by xgp** [comment]
A good starting point for understanding how the internals are built are the `io.phasetwo.service.model` classes `OrganizationProvider` and `OrganizationModel`. 

You'll find partially completed code for teams all over the place. Off of the top of my head, there are a few places that need to be extended:
- Add team methods to `OrganizationModel` (e.g. `getTeams`, `getTeam(name)`, `addTeam(team)`, `removeTeam(name)`, etc.)
- Add a `TeamModel` interface and implementation that exposes the underlying entity.
- Update the `TeamsResource` stub to use the updated model. (right now the commented out code uses an old strategy for data access)
- Create a `TeamResource` for using teams and managing membership
- Update `OrganizationResource` with methods for getting/creating teams.

You'll find a lot of examples you can use that are similar to how attributes, domains, members, etc. are related to Organizations. Thanks for any help you can give!
