### ISSUE TITLE
Invite link is not being injected into Organization Invite email in the default plain text template.

### ISSUE THREAD

**Issue by DamienTehDemon** [p2-inc/keycloak-orgs#140]
I am having an issue getting invites for organizations working properly. I have set up my keycloak instance with valid information to send emails according to the documentation. I am receiving the emails that are sent by keycloak no problem. The content of the email does not contain a link to accept the invitation though. I can see the variable in both the HTML and Plain Text default templates. What could be causing this?

Also why would it be using plain text instead of html?

**Comment by xgp** [comment]
The URL is set to the redirect you set in the API call to create the invitation. If you are not setting this value, you can also just add a default to your email templates. 

Not sure about HTML versus text. Can you post a full example of the raw email that is getting sent so we can debug?
