### ISSUE TITLE
OIDC IdP -> Organization linking broken in Admin UI

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-orgs#156]
There appears to be a bug in the orgs Admin UI for linking orgs to idps when using OIDC idps. The code is clearing the `config` params from the source JSON that are empty (but not null) before sending the update, and that appears to be causing the Keycloak `/admin/realms/{realm}/identity-provider/instances/{idp-id}` endpoint to throw the 409. 
1. We should make sure to preserve all fields that are empty
2. Also, `syncmode` has a typo, and should be `syncMode`

**Comment by pnzrr** [comment]
Fix pushed into keycloak repo
https://github.com/p2-inc/keycloak/commit/6b4c8407545aad9d6a4fd8074899be4fc2f6b714

Can close once verified.
