### ISSUE TITLE
Set a "attribute" template for all Organizations?

### ISSUE THREAD

**Issue by andreknieriem** [p2-inc/keycloak-orgs#162]
Hi there. I am newly to your plugin and first want to thank you for your work. I just want to know, if there is a way to pre define attributes to use in every organization? For example all of our organitations have an address. So I need zip,city,address,country,state for every organization. If I create a new organization I have to add the same fields again and again and there is lot of room for errors.

Best regards!

**Comment by xgp** [comment]
There is not currently a feature like that. I think what you're hoping for is something like the "Declarative User Profile" for User attributes. However, nothing like that has been implemented.
