### ISSUE TITLE
Can not accept the invitation to Organization.

### ISSUE THREAD

**Issue by akamishima99** [p2-inc/keycloak-orgs#166]
I can not accept the invitation to Organization.
The following, send the invitation mail with my application login url and receive the below mail and access the key cloak login window via the redirection by the my application. I can the login but not accept the user to a organization and can not get the organization information by my application.

![invitaton](https://github.com/p2-inc/keycloak-orgs/assets/108124252/9d20b6e5-795a-4732-8bc0-02e77648647c)
![mail](https://github.com/p2-inc/keycloak-orgs/assets/108124252/216a60cf-635b-4f95-b77e-840b2aea4405)

How do I accept an invitation to my organization?

**Comment by xgp** [comment]
Did you enable the invitation required action? It must be enabled in the admin UI in Authentication->Required Actions.

**Comment by akamishima99** [comment]
Yes, enable the setting as the following but can not accept the invitation.
![invitation](https://github.com/p2-inc/keycloak-orgs/assets/108124252/d868bf69-6979-4ec8-a364-f103e8cdc229)

**Comment by xgp** [comment]
Turn on `DEBUG` log level to see what is happening here: https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/invitation/InvitationRequiredAction.java#L28

**Comment by lsmith77** [comment]
I might be seeing the same issue. I have tried both enabling `Invitation` within the `Required actions` as well as customizing the browser flow to add `Invitation`.

However when a user registers nothing seems to be triggered, ie. the user is registered but is never asked to accept/reject invitations.

**Comment by xgp** [comment]
Can't repro. Please turn on `DEBUG` logging and see if that log message indicating the `evaluateTriggers` appears. I'll close this until I can get someone to send me logs and a way to reproduce. A comprehensive list of steps, or even a video would be great.

**Comment by lsmith77** [comment]
Is this the debug info you are looking for?

```
lab-keycloak-keycloak-1      | 2024-02-07 10:59:37,178 INFO  [io.phasetwo.service.auth.invitation.InvitationRequiredAction] (executor-thread-129) InvitationRequiredAction.requiredActionChallenge called for realm example and user test10@example.com
lab-keycloak-keycloak-1      | 2024-02-07 10:59:37,178 INFO  [io.phasetwo.service.auth.invitation.InvitationRequiredAction] (executor-thread-129) No challenge
```

It seems like it doesn't reach https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/invitation/InvitationRequiredAction.java#L33 but I am not seeing any errors.

**Comment by xgp** [comment]
@lsmith77 Thanks for reiterating that. I can see this isn't explicitly documented anywhere. It is a default to require that an email address be _verified_, as it would present a security issue to allow anyone who uses an email address to register to join an organization without verifying that the user is the owner of that email address. Because of that, it is assumed that you are using invitations in conjunction with setting *Verify Email* as a _default_ Required Action.

I updated the readme to include that description: https://github.com/p2-inc/keycloak-orgs/commit/92ff45154645c76a90633468c6740f6434429209
