### ISSUE TITLE
how to pre-select invitee roles

### ISSUE THREAD

**Issue by lsmith77** [p2-inc/keycloak-orgs#167]
I am looking at https://phasetwo.io/docs/organizations/invitations#setup

```
It is possible to pre-select any roles for a user by selecting in the Admin UI, or passing the roles array in the API. This will automatically add the user to the given roles upon user creation and acceptance of the invitation.
```

Neither in the form (shown in the screenshot) to create invitations, nor when clicking on the 3 dots in the list do I see an option to pre-select roles for an invitee.

Do I need to enable something in order to be able to do this? Or is this only supported via the API?

**Comment by xgp** [comment]
Correct. That functionality isn't exposed in the Admin UI. It's only available in the API and org admin portal.

**Comment by lsmith77** [comment]
ok I will send a doc PR to clarify this as it currently sounds like it should be possible to do via the UI
