### ISSUE TITLE
Unknown error when I try to create user

### ISSUE THREAD

**Issue by slabiak** [p2-inc/keycloak-orgs#171]
I'm using free version of keycloack-orgs hosted in cloud in eu-central-1. When i try to create new user or chekc details of some users i see such error:
 (
<img width="973" alt="Screenshot 2024-02-11 at 11 00 55" src="https://github.com/p2-inc/keycloak-orgs/assets/16743238/93777168-e348-4a10-afb2-b3197737717a">

This error comes from call to:
GET https://euc1.auth.ac/auth/admin/realms/appointmentscheduler/users/profile/metadata
and resposne code is 500
`{"error":"unknown_error"}`
timestamp of my http call: Sun, 11 Feb 2024 10:00:32 GMT

Can you please help? it worked fine few months ago.

**Comment by xgp** [comment]
@slabiak We are aware of some problems with the "Declarative User Profile" preview feature in Keycloak not working properly after upgrades. Please try turning off the feature and then turning it on again. It's in _Realm Settings_ -> _General_
![image](https://github.com/p2-inc/keycloak-orgs/assets/244253/46d56a00-f428-4568-85eb-e3ceeaaf07fc)
