### ISSUE TITLE
How to create the keycloak-admin-client .jar file

### ISSUE THREAD

**Issue by evandro-melos** [p2-inc/keycloak-orgs#178]
Hey guys, I want to build the `keycloak-admin-client` jar file, but did not find how to do it in the readme file.

could someone help me with that?

thanks

**Comment by xgp** [comment]
That's distributed by Keycloak. You don't need to build it, just use it as a dependency. If you are trying to install this extension (and its dependencies in Keycloak), please see how we do it in the docker image.

**Comment by evandro-melos** [comment]
Thanks, I installed the Organization extension, but cannot see the Organization Menu, the tables, and roles  are in the database, maybe I miss understood how it works

**Comment by xgp** [comment]
The extensions to the admin UI are only distributed in the docker image. If you need to use it separately, I’d suggest just copying the jars out of the providers dir in the docker image.
