### ISSUE TITLE
Enduser can fetch all organizations from api?

### ISSUE THREAD

**Issue by jaakkom** [p2-inc/keycloak-orgs#183]
Is there supposed to be some kind of authorization on  /orgs api? Currently anyone can fetch organizations with valid token. I think it should be somehow limited, now it reveals all "organizations" to all endusers.

**Comment by xgp** [comment]
https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/resource/OrganizationsResource.java#L99

Can you please show an example request for which a user without the view permission can call this so we can reproduce? Thanks.

**Comment by jaakkom** [comment]
Confirmed, it only shows organizations where user belongs to, just like orgs/me but different payload. My fault!
