### ISSUE TITLE
Auto-mapping to an Organization based on email domain

### ISSUE THREAD

**Issue by alexanderhofstaetter** [p2-inc/keycloak-orgs#190]
we have the understanding, that when a user logs in, and uses a org-verified domain, that the user is auto-added to the correct org.

Is there such an auto logic? Or do we have to map each user separately?

**Comment by alexanderhofstaetter** [comment]
Thanks!

We have the following use case why we are evaluating the use of `keycloak-orgs` at the moment.

We have a multi-tenant SaaS, where every customer logs in with their Azure AD (Microsoft) tenant as trusted SSO.

Currently in every SaaS environment we add a custom Azure IdP OAuth application in the customer tenant to use federated login.

We want to move to a cloud-based SaaS approach, where we have one keycloak as our Cloud IdP, with an single Microsoft OAuth Application (allows multi tenant), so every organization logs in via their own Microsoft account, but in our tenant.

So every user (of all orgs) use the same Social IdP. We now want to allow login with the same IdP but automap the user based on their email domain to the correct org. 

We trust the email domain, as there is no manual way to register, only with the SSO approach.


I am trying on getting some infos of this can be done with a custom JS authenticator - but I currently lack the knowledge on where to add such logic.

Thanks!

**Comment by xgp** [comment]
I would suggest doing it as a Required Action. There's some good documentation here https://www.keycloak.org/docs/latest/server_development/index.html#required-action-walkthrough

**Comment by alexanderhofstaetter** [comment]
Thanks for the tip! we implemented it as custom authenticator that matches users to orgs based on email (via IdP SSO) which we use in every auth via a custom post login flow the the IdP.

If somebody is interested in more details or the plugin I am happy to share!

**Comment by xgp** [comment]
Thanks for the update @alexanderhofstaetter 

We do a similar thing in the `OrgAddUserAuthenticatorFactory`:
https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/OrgAddUserAuthenticatorFactory.java

Feel free to PR your addition if you think others would be helped by it.
