### ISSUE TITLE
Identity Providers tab in orgs admin UI performance issues

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-orgs#198]
- For large sizes (100's of IdPs), we need a better way to select the active one, tbd how
- And for displaying the currently active one, we should update to use `/realms/{realm}/orgs/{orgId}/idps`

**Comment by xgp** [comment]
Clarification: The bug here is that we don't even show the selected IdP when it's not in the first "page", because we currently show the active one by matching against the list. So let's prioritize updating to use the orgs idps endpoint, and then we can figure out how to deal with paging afterwards.

**Comment by xgp** [comment]
@pnzrr We should work off the `23.0.1_orgs_admin_ui` branch for this, and then port any changes into the `24` branch currently underway.

**Comment by xgp** [comment]
@pnzrr We should also discuss how we want the update logic to work, and make sure we're implementing it correctly from the UI. See https://github.com/p2-inc/keycloak-orgs/issues/174#issuecomment-1948699543

**Comment by pnzrr** [comment]
https://www.keycloak.org/docs-api/24.0.1/rest-api/index.html#_get_adminrealmsrealmidentity_providerinstances

**Comment by pnzrr** [comment]
Priority 1: https://github.com/p2-inc/keycloak/pull/242

**Comment by pnzrr** [comment]
Priority 2: https://github.com/p2-inc/keycloak/pull/243

**Comment by pnzrr** [comment]
- /link should allow idp stealing from other organizations
- create an /unlink endpoint that removes the organization association from the idp
- link and unlink should only be available to users with the realm-management role of manage-organizations and not allowed for default organization roles, even manage-identity-providers
- On "Assign" in the Admin UI IdP<->org association modal, the idp should be checked for previous organization assignment, and the user warned
- link and unlink should not disable the idp in the case of reassignment or un-assignment
- Add more metadata to detail: enabled/disabled, if assigned to IDP
- Clean up UI just a bit more on the tab

**Comment by pnzrr** [comment]
https://github.com/p2-inc/keycloak-orgs/pull/206

**Comment by pnzrr** [comment]
Updated https://github.com/p2-inc/keycloak/pull/244
