### ISSUE TITLE
Unable to Configure SSO Using idp-wizard Extension

### ISSUE THREAD

**Issue by andreiserheichuk** [p2-inc/keycloak-orgs#212]
Hello Team,

I am writing to seek assistance with configuring Single Sign-On (SSO) through the portal page using the idp-wizard extension in Keycloak.

I have deployed the quay.io/phasetwo/phasetwo-keycloak:23.0.3 image and followed the instructions provided in the documentation https://github.com/p2-inc/idp-wizard?tab=readme-ov-file. However, I am encountering difficulties as I am consistently receiving a "Page not found" error when attempting to redirect to the wizard resource.

Could you please provide further guidance or detailed instructions on how to configure SSO through the portal page using the idp-wizard extension? Additionally, if there are any specific troubleshooting steps I should take, I would greatly appreciate your advice.

Thank you for your attention to this matter. I look forward to your prompt response and assistance.

Best regards

**Comment by xgp** [comment]
@andreiserheichuk The `idp-wizard` was closed source until our `24` version of Keycloak. You will have to use the latest version, or fork and build the `idp-wizard` yourself.
