### ISSUE TITLE
Is there an ETA when support for KC 24 is added?

### ISSUE THREAD

**Issue by alexanderhofstaetter** [p2-inc/keycloak-orgs#214]
We would love to see it working with version 24 of keycloak. :)

**Comment by xgp** [comment]
Support for 24 was released last week. Are you seeing some specific issue?

**Comment by alexanderhofstaetter** [comment]
My fault! I did not checked the image tags - its already there and working fine! 24.0.2 is not yet supported, right?

**Comment by xgp** [comment]
@alexanderhofstaetter Thanks. Looking into it.

**Comment by xgp** [comment]
@alexanderhofstaetter This is fixed in `24.0.2.1711993006`
