### ISSUE TITLE
Cane we accept invitation with phone number as username and no email id ?

### ISSUE THREAD

**Issue by priyabrata-munshify** [p2-inc/keycloak-orgs#226]
We have a requirement in which user registers just by verifying phone number with OTP without any email . As per my knowledge invitation works only if user has a verified email. 
Is their any way in which we can send an invite using phone number and then the user can login using the same phone number and accept the invitation ?

**Comment by xgp** [comment]
I'm sure you could modify/extend this extension to do something like that, but no, it does not work that way out of the box. It makes an assumption about using email address.
