### ISSUE TITLE
Organisation admin is forbidden (403)

### ISSUE THREAD

**Issue by wootapa** [p2-inc/keycloak-orgs#23]
- Built container: `docker build -t p2keycloak .`
- Started container `docker run --rm --name p2keycloak -p 8090:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -e KC_HTTP_RELATIVE=/auth p2keycloak start-dev` 
- Enabled phasetwo admin theme in master realm
- Created new realm 'test'
- Created new organisation 'Customer A'
- Created new user 'foo'
- Assigned user to organisation
- Assigned user all roles in organisation
- Logged in with user 'foo' in admin console

Expected: Full control of organisation
Actual: 403 forbidden

<img width="1218" alt="403" src="https://user-images.githubusercontent.com/1934387/201658526-20d2e4db-c86f-4885-a48c-07856689881a.png">
<img width="1127" alt="user" src="https://user-images.githubusercontent.com/1934387/201658555-870ed704-4976-4b15-a0a9-dcacac0b9a58.png">
<img width="273" alt="user_roles" src="https://user-images.githubusercontent.com/1934387/201658582-13eeee6f-7cfb-4ab4-bdfd-c60d61c45cbf.png">

**Comment by xgp** [comment]
That is correct. The Keycloak Admin UI is not available for organization administrators.
