### ISSUE TITLE
[Discussion] Organizations UI - Can't see the left bar of organizations

### ISSUE THREAD

**Issue by benlahav** [p2-inc/keycloak-orgs#230]
I've added these extensions to keycloak 24.0.0 running in docker container into `/providers` dir:
 - keycloak-orgs-0.72
 - keycloak-admin-client-24.0.0
 - phasetwo-admin-portal-0.29

I do have organization based data rendered into the UI but not an organization tab\menu to manage orgs in one realm context.  
What am I missing?

I've added this below dockerfile to [this](https://github.com/eabykov/keycloak-compose) compose repo and i'm building the image by the Dockerfile (`build: .`):  
```yaml  
FROM quay.io/keycloak/keycloak:24.0.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
ADD --chown=keycloak:keycloak ./providers/keycloak-orgs-0.72-SNAPSHOT.jar  /opt/keycloak/providers/keycloak-orgs.jar
ADD --chown=keycloak:keycloak ./providers/org.keycloak.keycloak-admin-client-24.0.0.jar  /opt/keycloak/providers/keycloak-admin-client.jar
ADD --chown=keycloak:keycloak ./providers/phasetwo-admin-portal-0.29-SNAPSHOT.jar  /opt/keycloak/providers/phasetwo-admin-portal.jar
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

**Comment by xgp** [comment]
You would need to go into the `Realm Settings -> Themes` and select `phasetwo.v2` for the admin theme. 

However, you will have serious problems trying to get this working in your own image. There's an explanation we have in a PR (https://github.com/p2-inc/keycloak-orgs/blob/080a5af765bb6140cf4c242e1333a506de3abfb6/README.md#installation) but we suggest using the [Phase Two Docker image](https://quay.io/repository/phasetwo/phasetwo-keycloak).
