### ISSUE TITLE
Getting cookie error on second browser tab

### ISSUE THREAD

**Issue by prifulnath** [p2-inc/keycloak-orgs#233]
Hello.

I am doing some testing on user actions setup. While i am trying to check this i found an error message "Cookie not found. Please make sure cookies are enabled in your browser."

![image](https://github.com/p2-inc/keycloak-orgs/assets/15168579/42b438f6-99c9-4d0a-97b1-38e80dce74b3)

### Steps to reproduce,
- Take login page in one tab
- Click on any expired user action mail link.
- It will show "Action expired" page.
- Click on go to login.
- This will show the message "Cookie not found. Please make sure cookies are enabled in your browser."

I found the same issue asked in [keycloak repo](https://github.com/keycloak/keycloak/issues/21451) , so tested with the latest keycloak it was working as expected. But when i am using latest phase2 it is showing the same error.

Is there anyway i can avoid this message and redirect to login page, from action expired page? or am i doing something wrong here?

**Comment by xgp** [comment]
@prifulnath Thanks for the report. Can you please check the image version you are using and paste it here? When using the most recent version (`24.0.4.1715362488`) and your instructions, I'm not able to reproduce.

**Comment by prifulnath** [comment]
@xgp I am right now using 24.0.2 version.

`FROM quay.io/phasetwo/phasetwo-keycloak:24.0.2`

I will try with 24.0.4 as well.

**Comment by prifulnath** [comment]
Issue occur when I added a **_back to login button_** in Action expired page. It is happening even in the 24.0.2.
