### ISSUE TITLE
Can I have different values for an organisation attribute for different users ?

### ISSUE THREAD

**Issue by priyabrata-munshify** [p2-inc/keycloak-orgs#239]
I have a bank organisation say ABC Bank. I have the attribute 'branch' which can have values 'branch1' or 'branch2' or 'branch3'.
How can I assign different branch values to different users ?

Is there any way I can assign value to organisation attribute dynamically ?

Or is there any way I can map a User attribute value to the organisation attribute ?

**Comment by xgp** [comment]
This is not supported.
