### ISSUE TITLE
Misunderstanding about licence and Idp wizard

### ISSUE THREAD

**Issue by ClementGayet** [p2-inc/keycloak-orgs#242]
Hi,

I've seen closed issues about 404 on Idp Wizard until version 24, i currently use the latest version and can't access this feature either.
Also i've seen on this issue https://github.com/p2-inc/keycloak-orgs/issues/212 that you suggest to fork and build the wizard package by ourself.
By reading the licence i understand that we can't alter, remove, or obscure any licensing feauture ? Also where we can find feature under licence ?

best regards,

**Comment by xgp** [comment]
> i currently use the latest version and can't access this feature either.

Can you please describe your configuration and what you are doing to try to access the idp wizard?

**Comment by xgp** [comment]
> where we can find feature under licence ?

Each repository in our GitHub has a `COPYING` file that indicates the license. E.g. https://github.com/p2-inc/idp-wizard/blob/main/COPYING

**Comment by ClementGayet** [comment]
I just takes the image on the public repository `[quay.io/phasetwo/phasetwo-keycloak:latest]`, when i want to access the IdpWizard i got bunch of 404 repsonses and no log in the keycloak. But i've seen that this is due to licence no ?
Here are the screenshots and file
![image](https://github.com/p2-inc/keycloak-orgs/assets/37474086/ff9b08ae-c45a-446e-8ff4-cd8101f740b4)

**Comment by xgp** [comment]
I'm not able to reproduce. Here are my steps:
1. start using the `24.0.4` docker image
```
docker run --name phasetwo_test --rm -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    -e KC_HTTP_RELATIVE_PATH=/auth \
    quay.io/phasetwo/phasetwo-keycloak:24.0.4 \
    start-dev \
    --spi-email-template-provider=freemarker-plus-mustache \
    --spi-email-template-freemarker-plus-mustache-enabled=true \
    --spi-theme-cache-themes=false
```
2. log into `http://localhost:8080/auth/` using the `admin:admin` creds
3. navigate to the Clients section
4. click on the `http://localhost:8080/auth/realms/master/wizard/` link
5. see this screen in a new window
![image](https://github.com/p2-inc/keycloak-orgs/assets/244253/43d7831e-6758-4fd4-8e0b-5d6e6644db0a)

**Comment by ClementGayet** [comment]
Okay right, it seems that if we don't set KC_HTTP_RELATIVE_PATH to /auth, the wizard is not working
Added the env var and it's working perfectly

**Comment by xgp** [comment]
Thanks. Issue moved to https://github.com/p2-inc/idp-wizard/issues/181
