### ISSUE TITLE
Space in realm name not allowed / error

### ISSUE THREAD

**Issue by corepay** [p2-inc/keycloak-orgs#247]
Did a fresh install via compose using `quay.io/phasetwo/phasetwo-keycloak:latest` image.

Prior to enabling the p2 admin theme I created a realm named Demo Tenant

Was back in master realm and enabled p2 admin theme.  When attempting ot return to Demo Tenant got error below.  Notice the urlencoding in the realm name %20

![image](https://github.com/p2-inc/keycloak-orgs/assets/48992923/61abe840-0f0a-4752-883f-b985703a0b26)

I created a new realm `Tenant` (no spaces) without a space and no problems or error.

Rebuilt a new Keycloak install and before creating any realms first thing I did was enable p2 admin theme.

Then created a new realm Demo Tenant and got the error screen above once again.  Create another realm `Tenant` (no spaces) no problem or error

**Comment by xgp** [comment]
Realm names with spaces should not be allowed. See https://github.com/keycloak/keycloak/issues/10181

**Comment by corepay** [comment]
Ah yes I see this is a KeyCloak issue - shoulda thought this through a little more. Thanks for the link I'll look over there a little more often.
