### ISSUE TITLE
Groups per organisation

### ISSUE THREAD

**Issue by janhaesen** [p2-inc/keycloak-orgs#25]
It would be nice to have the ability to have groups available per organisation. The reasoning behind it would be that in general Keycloak roles (to which I'd prefer to refer to  as permission, but won't for sake of terminology) will be grouped into a role, e.g. Admin, Support, Finance Ops, etc. This way this could be assigned to a user under the organisation. 

The idea would be that there's a general set of groups that are by default provided but can be amended (overruled/overridden) by the organisation, for instance because they'd want to make it more/less restrictive. This functionality is already available in Keycloak itself, but would be nice to have on an organisation level as well. 

Another way this is sometimes achieved, but likely would be less intuitive, is the composite roles in Keycloak.

**Comment by xgp** [comment]
https://github.com/p2-inc/phasetwo-java/pull/3

**Comment by xgp** [comment]
Closing in favor of https://github.com/p2-inc/keycloak-orgs/issues/48
