### ISSUE TITLE
Keycloak SSO for Multi tenant app

### ISSUE THREAD

**Issue by shkmaaz11** [p2-inc/keycloak-orgs#252]
I'm trying to implement multi-tenancy in Keycloak. 
I've added a realm and in that realm I have different organization say app1 and app2 with individual identity providers.
My question is that if I want SSO between these 2 apps how to achieve that?
If I login to app1 and move to app2 I shouldn't be asked to login in app2

**Comment by shkmaaz11** [comment]
@xgp Thanks for the response. That's what we're currently doing. But we want to isolate the tenants. And have one tenant as one org

**Comment by xgp** [comment]
I don’t really understand your use case. I’d recommend checking out the new multi tenancy feature in Keycloak 25. https://www.keycloak.org/2024/06/announcement-keycloak-organizations.html
