### ISSUE TITLE
Not able to see Organization Extension

### ISSUE THREAD

**Issue by ankit-akteena** [p2-inc/keycloak-orgs#253]
I am running the docker command from  https://quay.io/repository/phasetwo/phasetwo-keycloak

```
docker run --name phasetwo_test --rm -p 8080:8080 \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    -e KC_HTTP_RELATIVE_PATH=/auth \
    quay.io/phasetwo/phasetwo-keycloak:latest \
    start-dev \
    --spi-email-template-provider=freemarker-plus-mustache \
    --spi-email-template-freemarker-plus-mustache-enabled=true \
    --spi-theme-cache-themes=false
```

the container is running , i have set the theme as well to phasetwo.v2 but i dont the organization extention on my UI , are there any other steps i need to do to make it come up , i thought the docker image had all things included

<img width="1507" alt="image" src="https://github.com/p2-inc/keycloak-orgs/assets/173347254/52f0ab8c-71f2-47b8-8840-6cd14934d675">

**Comment by xgp** [comment]
Did you log out and log back in again? The admin UI doesn't load different themes without a new session.

**Comment by ankit-akteena** [comment]
yes did logout and login , also tried in incognito but still the same

**Comment by xgp** [comment]
Can't repro. Video of my exact steps:
https://github.com/p2-inc/keycloak-orgs/assets/244253/7a5cb7cc-eb09-42e9-afd2-9a1875c1d655

Couple of debugging ideas:
- make sure you are specifying the current image tag so you're sure docker is not caching an old one
- the admin theme must be set for the realm you are logging in as. I.e. you can't set it for the `Akteena` realm and then login as a `master` realm user and expect it to be there.

**Comment by ankit-akteena** [comment]
Ahh the second point was the issue , now it is working , Thanks for the video really helpful.
