### ISSUE TITLE
POST /orgs should return the newly created organization

### ISSUE THREAD

**Issue by michaeljauk** [p2-inc/keycloak-orgs#254]
When creating a new organization via the API the newly created organization is not returned in the response of `POST .../orgs`. This makes automating organization creation somewhat tedious, as it is necessary to find the newly created organization by name.

A much better solution would be to just return the properties of the created org (namely the `id`) in the response of the POST-request.

**Comment by xgp** [comment]
Incorrect. It's in the `Location` header. This is consistent with how Keycloak returns the new IDs when entities are created.
