### ISSUE TITLE
Member invitation email missing link

### ISSUE THREAD

**Issue by youssefbennour** [p2-inc/keycloak-orgs#257]
I've been trying to invite a user to an organization by email, the email is sent just fine, but the accept url is missing.
![image](https://github.com/p2-inc/keycloak-orgs/assets/48494859/c42e44e5-a3e2-4d21-ac5c-3ab45ff3ea19)

**Comment by xgp** [comment]
You either have to call the API with the `redirect_uri` set or change the template to add a link.

We have looked at the idea of making an action token link the default, but that hasn't been implemented yet.

**Comment by xgp** [comment]
https://github.com/p2-inc/keycloak-orgs/issues/224
