### ISSUE TITLE
keycloak hostname:v2 /admin used on "hostname" instead of "hostname-admin"

### ISSUE THREAD

**Issue by awoimbee** [p2-inc/keycloak-orgs#260]
When
* using the `phasetwo.v2` admin console theme
* on keycloak 25 using [the new hostname v2 config](https://www.keycloak.org/docs/latest/upgrading/index.html#new-hostname-options)
* with `hostname-admin` != `hostname`

Then one hits an issue similar to https://github.com/keycloak/keycloak/issues/30432 when loading the admin console.

TL;DR:
The javascript requests `<hostname>/admin/...` which should never happen as all resources in `/admin` should be accessed through `<hostname-admin>` (so `<hostname-admin>/admin/...`).

Requests:
![Screenshot from 2024-07-22 14-43-29](https://github.com/user-attachments/assets/eb20c858-10ab-4d1e-9add-119f6c77c434)

Bad request origin:
![Screenshot from 2024-07-22 14-43-02](https://github.com/user-attachments/assets/83dc4312-1874-4b30-9863-47778a104a33)

**Comment by xgp** [comment]
I think the issue is that the currently release `phasetwo.v2` admin ui jar is based on `25.0.0`. There is a PR in the containers repo with the new jar if you want to test it https://github.com/p2-inc/phasetwo-containers/pull/54
