### ISSUE TITLE
Automatically assign default roles via Add User To Org auth flow step?

### ISSUE THREAD

**Issue by michaeljauk** [p2-inc/keycloak-orgs#262]
Hey there,

i hope this is the right place to ask this.

I am trying to setup SSO and automatically assign users of a given IDP to their respective organization. This all works fine so far.

What I'm trying to accomplish: I want users that get created via SSO and assigned to their organization to have a set of default org roles automatically assigned to them.

I haven't found any documentation, that something like this is possible. Does anyone of you guys know something about that?

**Comment by xgp** [comment]
There is not currently a built-in way to add default Organization Roles. We do this either by event listener or on first login. 

However, this is a good suggestion, and we'd accept a PR in this regard.

**Comment by michaeljauk** [comment]
@xgp Thanks for the swift answer. Could you clarify, what do you mean by "on first login"?

Is there a way to setup Keycloak/p2 to assign roles to a user on the first login?

**Comment by xgp** [comment]
@michaeljauk There is nothing built in. We just detect that the user has logged in for the first time (there are lots of ways to do this, but one we use is to either have a user attribute or a group that tags that they have logged in before) and then assign them to the default groups.
