### ISSUE TITLE
Question around Role & User management within an organization

### ISSUE THREAD

**Issue by randyn** [p2-inc/keycloak-orgs#265]
Hi there,

I'm currently evaluating multi-tenancy solutions within keycloak and came across phase two organizations which fulfills a lot of my goals. I did notice that with phase two organizations, if two users have the ability to manage users, they each have the ability to kick the other out.

My use case needs 3 classes of users:
* Class A - Manage all users in a given organization
* Class B - Manage Class B users and below in a given organization
* Class C - Unable to manage other users

Is this possible with phase two organizations?

**Comment by xgp** [comment]
>  if two users have the ability to manage users, they each have the ability to kick the other out.

Correct

Regarding your use cases:
- "Class A" is possible via the `manage-members` organization role
- "Class C" is the default without any organization roles
- Your "Class B" sounds like a tiering or hierarchy that isn't supported. You could create a custom organization role (e.g. `manage-members-in-class-b` and then build your own API to allow users with that role to manage other users with the same role. We've seen people building a "teams" concept using a similar approach.
