### ISSUE TITLE
Forgot password screen not coming

### ISSUE THREAD

**Issue by ankur-tj** [p2-inc/keycloak-orgs#266]
I have configured 'forgot password' to true at realm settings level and I am getting the 'forgot passsword?' button on the UI. When I click on this button, it makes an API call to /login-actions/reset-credential but doesn't return the forgot password screen. Instead, it returns the same login screen.

![image](https://github.com/user-attachments/assets/3f942141-ab7f-426a-999d-24f5912492b1)

This issue is only happening when I use Home IDP Discovery step. Below is the simplified version of my authentication flow to reproduce this issue.

![image](https://github.com/user-attachments/assets/d3a44265-c7da-4ceb-adb7-72c9a75fb3c5)

When I tried using the browser flow, it works fine and I get the forgot password screen on clicking of the button. I want to know how to make it work with IDP discovery step.

**Comment by xgp** [comment]
@rtufisi Can you take a look at this to reproduce with 
1. the current, released version
2. the new version you worked on
3. the basic home idp extension without our changes

?

**Comment by rtufisi** [comment]
Sure. I will look into it

**Comment by rtufisi** [comment]
Hei @ankur-tj . Could you provide us with additional information regarding this issue? 
I tried to reproduce the issue under the conditions that @xgp  mentioned but I couldn't manage it. 

Perhaps you can give the Home Idp Discovery step configs under the alias "alias212". 
Another think will be the version of keycloak you use. I'm trying to reproduce the issue on phasetwo-keycloak:25.0.1

So basically the repro steps I've tried are:
1. in the master realm create the Authentiation flow mentioned in the first comment.
2. activate the Reset password in the Realm settings
3. assign the authentication flow to the "account-console" client
4. create a test user and a set of credentials
5. Access {{domain}}/auth/realms/master/account/ and start the login flow


Could you please confirm you are experiencing the same behaviour?

**Comment by xgp** [comment]
Closing pending requested information. Please reopen if this is still an issue.
