### ISSUE TITLE
Executing an action on invitation accept

### ISSUE THREAD

**Issue by youssefbennour** [p2-inc/keycloak-orgs#268]
Hi,
I have a requirement to execute some operation on my application when a user accept an organization invtation he's been sent.
I have been reading the source code, but I can't find an event that's triggered on user invitation accept.
Does such an event exists ? If not, could you give suggestions on how I could approach this requirement ?

**Comment by xgp** [comment]
There are events emitted when the user accepts or rejects an invitation:

https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/auth/invitation/InvitationRequiredAction.java#L95-L111

**Comment by youssefbennour** [comment]
@xgp 
I was testing invitation to see the details of events so I can catch it, and I found that the triggered event is always of type CUSTOM_REQUIRED_ACTION_ERROR, even when the invitation is accepted and everything works fine :
![image](https://github.com/user-attachments/assets/ed10ff9b-c670-476e-92b3-e5b1d9431401)

What do you think ?

**Comment by xgp** [comment]
@rtufisi Can you try to reproduce? In prod for us this is working fine, but we are on an earlier version.

**Comment by youssefbennour** [comment]
I'm using  quay.io/phasetwo/phasetwo-keycloak:25.0.1

How to reproduce:
1 - Login to your keycloak server using admin credentials
2 - Navigate to your realm
3 - Create a new organization
4 - Invite an existing realm member by email
5 - Navigate to the account console and login with the invited user credintials.
6 - After successful login, accept organization(s) invitation(s)

Upon the last step, the logger logs a similar CUSTOM_REQUIRED_ACTION_ERROR as I've provided you with above.
I've tried it more than once, but the it always triggers the same error event.

**Comment by rtufisi** [comment]
On it

**Comment by rtufisi** [comment]
Hei @youssefbennour ,

I've tried to reproduce the issue you mentioned.

If a user accepts an organization invitation a successful event is emitted like in the following screenshot:

![Screenshot from 2024-08-19 14-53-23](https://github.com/user-attachments/assets/b805d7f5-9b32-4cac-b3b3-14cc5273bd72)

If a user accepts the invitation to join a organization a successful CUSTOM_REQUIRED_ACTION event is emitted as in the following example:

`August 19, 2024 at 2:51 PM	[fc1f95e2-63fa-4e41-aff1-86cf6e1eb38a](http://localhost:8080/auth/admin/master/console/#/test-realm/users/fc1f95e2-63fa-4e41-aff1-86cf6e1eb38a/settings)	
CUSTOM_REQUIRED_ACTION	
172.20.0.1	security-admin-console
invitation_id 042325a2-7b33-4374-a148-b10e8fe6893a
auth_method openid-connect
org_id  18e5d4bf-ad0d-432a-929e-55f11df54387
custom_required_action  invitation-required-action
response_type code
redirect_uri http://localhost:8080/auth/admin/test-realm/console/
remember_me false
code_id d3266b00-9dbd-4a91-b844-5a537bc44c56
response_mode query
username  test
`

At the end of the required action execution to perform a cleanup the invitation is removed and a "CUSTOM_REQUIRED_ACTION_ERROR" event is emitted to signal that the invitation was consumed.


Steps I've used to reproduced
I'm using quay.io/phasetwo/phasetwo-keycloak:25.0.2(25.0.1 has a UI bug in the events tab as described in the bug: https://github.com/keycloak/keycloak/issues/30306)

How to reproduce:
1 - Login to your keycloak server using admin credentials
2 - Navigate to your realm
3 - Create a new organization
4 - Invite an existing realm member by email
5.- Enable "Invitation" in the realm required action settings
6. - Navigate to the account console and login with the invited user credentials.
7. - After successful login, accept organization(s) invitation(s)


please let me know your thoughts

**Comment by youssefbennour** [comment]
@rtufisi 
I will test it again, I'm not sure whether the succeeding event was emitted in my case or not.
Thanks.
