### ISSUE TITLE
Need help moving from organisation not sharing users model to Phasetwos shared users organisation model

### ISSUE THREAD

**Issue by keshavkaul** [p2-inc/keycloak-orgs#269]
We have an on prem multi-tenant authentication system that does not share users. We want to move to keycloak with Phasetwo's Organisation extension. But from the docs it seems that all Organisations can share users. I wanted to understand what possible issues we may face when migrating the users to keycloak. One problem i can foresee is of same username conflict between organisation. Any suggestions for resolving this problem?

**Comment by xgp** [comment]
This extension is designed to allow Users to be members of multiple Organizations within a single Realm. Realms don't allow multiple Users to have the same username. If you are looking for isolated multi-tenancy, this extension probably isn't for you. I'd suggest Realm per tenant.

**Comment by keshavkaul** [comment]
@xgp Thanks appreciate it, so any suggestions on how to handle performance impact on Keycloak having realms greater than 100? I'm not looking for a solution but any hint or direction would be nice.

**Comment by keshavkaul** [comment]
@xgp Does PhaseTwo SaaS offering support realm per tenant scenario?

**Comment by xgp** [comment]
No.
