### ISSUE TITLE
How to declaratively configure the custom admin UI theme?

### ISSUE THREAD

**Issue by phamann** [p2-inc/keycloak-orgs#27]
To use this extension implementors must set the Keycloak admin console theme to the custom `phasetwo.v2` theme in order to make organization UI pages visible/useable. This can be achived manually via the admin console and the preference is then persisted to the database for subsquent uses. 

Ideally we would like to declaritively configure the `phasetwo.v2` ui as the _default_ UI on application boot, either via an environment variable, realm import, or similar. I have attempted to work out how to do this and researched many forum posts, documentation etc without success.

How does phasetwo solve this problem? Do you know of a way to declarivitely configure the default admin ui?

Apologies if this is the wrong location/repository to ask such a question, please feel free to redirect me if wrong. 

Many thanks.

**Comment by xgp** [comment]
You can set the admin theme a few ways:
1. If you are referring to the `master` realm, you can import a realm config file during first startup that specifies the `phasetwo.v2` theme. Docs on how to do that are in the Keycloak guides: https://www.keycloak.org/server/importExport
2. Any time you create a realm (non-`master`), you can give it a realm config file that specifies the `phasetwo.v2` theme.
3. If you are applying configuration to existing realm, you can use something like this https://github.com/adorsys/keycloak-config-cli to set the theme.

However, I don't know of a way to make it the "default" as you say.
