### ISSUE TITLE
Organizations UI with page size of 100 is showing only the first 100 organizations

### ISSUE THREAD

**Issue by ebenoit26** [p2-inc/keycloak-orgs#272]
Hi,

We currently use the keycloak ui version 25.0.4_orgs_admin_ui with Keycloak 25.0.5.

In the organizations page list if we use 100 items per page only the first 100 organizations are shown, the next page arrow is disabled. However if we use 50 items per page we see all the organizations, the next page arrow is enabled. 

Also the page label texts are a little weird, like 'orgList', 'orgExplain', 'createOrg', 'searchForOrg'... it is like function names more than label texts. 

See screenshot for more details.

We previously used the version 21.0.2_orgs and we did not have any of these problems. 

Thanks in advance!
![keycloak-ui-1-100](https://github.com/user-attachments/assets/ee5d743d-4817-4a63-87b5-bf5c11a1d5c7)
![keycloak-ui-101-110](https://github.com/user-attachments/assets/04c0a831-fdf6-4694-a628-988c33db8195)

**Comment by xgp** [comment]
Are you building this on your own or are you using the [phasetwo image](https://quay.io/repository/phasetwo/phasetwo-keycloak)?

**Comment by ebenoit26** [comment]
We are using the phastwo plugin into our keycloak container.

**Comment by xgp** [comment]
I'd recommend using the most recent  [phasetwo image](https://quay.io/repository/phasetwo/phasetwo-keycloak) and see if you can reproduce the issues. We don't support custom images. Please reopen with more information once you've tried it with that image.
