### ISSUE TITLE
Questions about organization events

### ISSUE THREAD

**Issue by shehabghazy** [p2-inc/keycloak-orgs#273]
Hi everyone,

First of all, I’d like to thank you for your efforts in developing this fantastic extension.

I have two questions regarding my Keycloak configuration. In my realm, I have defined several groups, such as `user`, `super-user`, and `admin`.

Role Creation: Is it possible to create an event that automatically adds roles -inside org- with the same names as these groups when a new organization is created?

Group Assignment: Can I assign a user to specific groups immediately after creating an organization based on organization roles? So it will be something like a mapper from organization roles to realm groups

Any guidance or examples would be greatly appreciated! Thank you

**Comment by xgp** [comment]
(transferred to `keycloak-orgs` as the events repo isn't related)

> Role Creation: Is it possible to create an event that automatically adds roles -inside org- with the same names as these groups when a new organization is created?

Please see the [events documentation](https://github.com/p2-inc/keycloak-orgs/blob/main/docs/events.md) for more information about what events are emitted for what changes. You can write an [event listener](https://www.keycloak.org/docs/latest/server_development/index.html#_events) to do whatever you want on an event. 

> Group Assignment: Can I assign a user to specific groups immediately after creating an organization based on organization roles? So it will be something like a mapper from organization roles to realm groups

As above, write an [event listener](https://www.keycloak.org/docs/latest/server_development/index.html#_events) for custom functionality like this.
