### ISSUE TITLE
Add Organizations tab to User in Admin UI

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-orgs#283]
List the orgs the user is a member so it's easy to see by user where they are a member.

**Comment by pnzrr** [comment]
<img width="1936" alt="image" src="https://github.com/user-attachments/assets/c686f33a-c7fd-4dcf-92a1-ecee04c1e812">

Kaboom

https://github.com/p2-inc/keycloak/commit/146c7be4e37a40d9d59b8144547c863762734388

Currently in the 26.0.2 branch

**Comment by pnzrr** [comment]
FYI - translations are in there but I didn't build the container.
