### ISSUE TITLE
Number of users per organization

### ISSUE THREAD

**Issue by shehabghazy** [p2-inc/keycloak-orgs#286]
First of all.. thanks a lot for the great effort that you have done in this extension 

I have a SaaS app, and I need to restrict the number of users based on the subscription package. Is there a way to limit the number of users per organization?

best regards

**Comment by pnzrr** [comment]
@shehabghazy you could use the memberships count https://phasetwo.io/api/get-organization-memberships-count/ to track numbers of users then limit access to sending invites or adding new members through your application

the extension itself doesn't support a member limit

**Comment by shehabghazy** [comment]
@pnzrr noted .. your quick response is really appreciated .. is there any plan to implement such a feature ?

**Comment by pnzrr** [comment]
We don't have any present plans to implement such a feature but are always open to PRs.
