### ISSUE TITLE
500 error when calling endpoint

### ISSUE THREAD

**Issue by fgarioli** [p2-inc/keycloak-orgs#3]
I’m trying to generate the jar file from the source, but I’m facing some difficult things. I had to install keycloak from source to get some missing dependencies, so after that I could compile and generate the jar file.
The problem is when I put the jar on my keycloak test instance, and call some endpoint related to the library.
The response status is 500. I look at keycloak log to see what happened and it asks for some dependencies. So, it seems like the library compilation process it was no ok on maven.
Could you help me please?

The log file is attached to the issue.
If you need any other information, just let me know.

Thanks!

[keycloak.log](https://github.com/p2-inc/keycloak-orgs/files/8728822/keycloak.log)

**Comment by xfh** [comment]
I've made the same experience :-)

I managed to get it fixed by adding the Keycloak Admin Client JAR to the providers. The REST API Resources are making use of the admin client to call other Keycloak REST APIs.

**Comment by xfh** [comment]
BTW. somehow the URLs are exposed differently that the default REST APIs. I didn't manage to get it work with e.g. `kcadm.sh get orgs -r myrealm`. Keycloak 18.0.0 adds  an `admin/` path, where as this extension is binding directly to the root.

Here an example:
`curl -H "Authorization: Bearer ${token}" http://localhost:8080/realms/myreal/orgs`

**Comment by fgarioli** [comment]
> Keycloak Admin Client

Thanks! It works now!

**Comment by xgp** [comment]
@fgarioli Sorry I missed this one. Yes, you need the admin client jar to run this. I'll add it to the docs.

**Comment by xgp** [comment]
Added to README in [f12ce36](https://github.com/p2-inc/keycloak-orgs/commit/f12ce368ba1355b7db16bca69bed48e048df5e48)
