### ISSUE TITLE
why i can not see phasetwo.v2 theme in Admin console theme

### ISSUE THREAD

**Issue by jsshizhan** [p2-inc/keycloak-orgs#34]
keycloak 19.0.3

**Comment by xgp** [comment]
In order to use the `phasetwo.v2` theme in the admin console, log in, navigate to **Realm settings** > **Themes**, select `phasetwo.v2` as the _Admin console theme_, and click _Save_. Log out and log back in again for the changes to take effect.

**Comment by jsshizhan** [comment]
![image](https://user-images.githubusercontent.com/8943661/217197291-2efeacc1-767d-4581-a175-bfe81e7e5566.png)

**Comment by xgp** [comment]
The `phasetwo.v2` admin console theme is not part of this extension. In order to use it, either use the [docker image](https://quay.io/repository/phasetwo/phasetwo-keycloak), or build it from our [keycloak-ui branch](https://github.com/p2-inc/keycloak-ui/tree/20.0.1_orgs).
