### ISSUE TITLE
Docker example?

### ISSUE THREAD

**Issue by Ross-ForAllSecure** [p2-inc/keycloak-orgs#5]
Very interested in this project, but I'm having a heck of a time getting it to run.  Any possibility of cooking up a Dockerfile or even a docker-compose setup?  

Looking forward for taking this code for a spin!

**Comment by Ross-ForAllSecure** [comment]
I have some semblance of a docker setup running in pull request https://github.com/p2-inc/keycloak-orgs/pull/6 .  

I'm seeing messages like 
```
[io.phasetwo.service....
```
So, it appears to be installed.

Unfortunately when I click on the `Authentication` page, I do not see the "Invitation" Flow, nor the "Invitation Browser" under the dropdown.

![image](https://user-images.githubusercontent.com/95310677/170392658-689d6f46-4e6a-485e-9942-b75180f790e9.png)


Any chance of looking at that `Dockerfile` to see what I'm doing wrong?
https://github.com/p2-inc/keycloak-orgs/pull/6/files#diff-2f47544ee814d438d1fe01f45ca3b4f8f71c9cbced0248423745db824de244ab

**Comment by fgarioli** [comment]
I had to create a new flow like the docs image and override it on the client. It worked for me.

**Comment by Ross-ForAllSecure** [comment]
Thanks @fgarioli .  I didn't catch that I had to run through all that configuration.

**Comment by xgp** [comment]
You'll need to recreated the flow here: https://github.com/p2-inc/keycloak-orgs#invitations
