### ISSUE TITLE
Invitation flow

### ISSUE THREAD

**Issue by grinay** [p2-inc/keycloak-orgs#59]
May you please suggest the steps how to achieve the next flow. 
Organisation invites user, and user receives invitation link, then user follows by that link and land to registration page which saying about invitee and prefill email on registration page. 
Currently I don't really understand yet how it works. It sends email on invitation , but email has no link inside. Also out tenants have no dedicated domains.

**Comment by xgp** [comment]
It depends on how you are sending an invitation, but you can set the `redirect_uri` in the request, which will set the link in the email. Take a look at this discussion for more information on how it works now, and some suggested changes: https://github.com/p2-inc/keycloak-orgs/issues/49#issuecomment-1473643933

**Comment by grinay** [comment]
> It depends on how you are sending an invitation, but you can set the `redirect_uri` in the request, which will set the link in the email. Take a look at this discussion for more information on how it works now, and some suggested changes: [#49 (comment)](https://github.com/p2-inc/keycloak-orgs/issues/49#issuecomment-1473643933)

Currently I'm trying to send invitation right from the keycloak itself. I'm not put anything into redirect url.
