### ISSUE TITLE
How to configure an authentication flow to allow redirection based on email domain?

### ISSUE THREAD

**Issue by matheushent** [p2-inc/keycloak-orgs#68]
Hello. First, awesome work throughout this project.

The [documentation](https://phasetwo.io/docs/organizations/identity-providers/#:~:text=When%20an%20authentication%20flow%20is%20configured%20properly%20to%20allow%20for%20redirection%20based%20on%20email%20domain%2C%20these%20are%20the%20domains%20that%20will%20be%20used%20to%20look%20up%20the%20associating%20identity%20provider.) states that it is possible to configure an authentication flow in which the users input an email and then Keycloak will check out which organization has the domain verified.

Which are the steps in the authentication flow that enable this behavior indeed?

**Comment by xgp** [comment]
https://github.com/p2-inc/debug-app

It's in the `frontend/` folder.

**Comment by matheushent** [comment]
I appreciate the help, thank you very much!
