### ISSUE TITLE
How to get the Invitation authentication flow working?

### ISSUE THREAD

**Issue by matheushent** [p2-inc/keycloak-orgs#84]
So, what I've been trying is to use the `Invitation` authentication flow. Suppose I have a user named `foo` that was invited to the `boo` organization. How do I properly set an authentication flow to check the outstanding invitation and automatically add the user `foo` to the `boo` organization if the invitation exists?

So far I couldn't get this flow working. I'm thinking about this can be done in the post login flow, maybe adding some steps after... idk
<img width="1030" alt="image" src="https://github.com/p2-inc/keycloak-orgs/assets/45343359/ad12d2a6-68c7-4a5b-9449-51b0669df571">

**Comment by xgp** [comment]
For most use cases, the `Invitation` authenticator doesn't need to be in a flow. It should be sufficient to set the `Invitation` required action to `Enabled` in *Authentication*->*Required Actions*
![image](https://github.com/p2-inc/keycloak-orgs/assets/244253/c454cfaa-e50f-4a3c-94b4-87e9e85801d6)
It will automatically run on every login and add itself if the user has outstanding invitations.

**Comment by matheushent** [comment]
I think this detail should be clearly mentioned in the public documentation.

Other than that, I could get the flow working, thank you!!

**Comment by xgp** [comment]
Updated. https://github.com/p2-inc/keycloak-orgs/tree/main#invitations
See if you think that language is more clear. Thanks for the help and feedback.

**Comment by matheushent** [comment]
amazing mate, very helpful. Thank you!!
