### ISSUE TITLE
Adding keycloaks current filter options to api-endpoints

### ISSUE THREAD

**Issue by paulwer** [p2-inc/keycloak-orgs#88]
Hey @xgp,
would it be possible to add filter options like "q" f.ex. for the attribute based filtering to the existing api-endpoints?
- q :: A query to search for custom attributes, in the format 'key1:value2 key2:value2'
- <param-name> :: for queriing fields of the organization

It would be realy nice to have the same syntax of queriing data from your extensions, that from keycloak itself.

tank you very much.

**Comment by xgp** [comment]
Thanks for the suggestion. Not on our roadmap, but happy to take a PR.

**Comment by paulwer** [comment]
@xgp I am currently not that into java-development, but I would suggest looking at
https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java to implement the missing fields. I think in the most cases just copy/paste is required.

**Comment by phamann** [comment]
Funnily enough, we also discovered the need for this functionality this week. So I've just submitted #93 to introduce the ability to seach for orgs based on their attrbutes using the same pattern as the user search: `GET /:realm/orgs?q=foo:bar` (like @paulwer suggested).

Hope this helps 😄

**Comment by xgp** [comment]
Thanks @phamann ! Will merge once we've run some other regression tests here.
