### ISSUE TITLE
Feature request: endpoints for invitations

### ISSUE THREAD

**Issue by matheushent** [p2-inc/keycloak-orgs#90]
Hi.

This is an issue to request essentially two endpoints related to invitations:

1. GET {realm}/orgs/{orgId}/invitations/{invitationId}
2. GET {realm}/orgs/{orgId}/invitations/count

As it is trivial to notice, [1] would fetch a single invite by its ID and potentially return 404 in case it doesn't exist. Similarly to `GET {realm}/orgs/{orgId}/members/count`, [2] is an endpoint to return the number of existing invites.

The addition of these two endpoints would enable a more powerful pagination in any backend that depends on querying the invites.

In advance, thank you!

**Comment by xgp** [comment]
@matheushent thank you for the suggestion. We have received a lot of feature requests to add counting and pagination to the list methods. It sounds like this is being used for larger volumes than we originally expected (which is great!). However, we're focused on some other tasks right now, so we can't prioritize this right away. Feel free to file a PR if you can do it.

**Comment by xgp** [comment]
`GET {realm}/orgs/{orgId}/invitations/{invitationId}` is getting done via https://github.com/p2-inc/keycloak-orgs/issues/151

**Comment by matheushent** [comment]
That is amazing. Thank you for that implementation!!
