### ISSUE TITLE
Organizations and customer's tenant

### ISSUE THREAD

**Issue by sumandas15** [p2-inc/keycloak-orgs#92]
First, let me acknowledge your outstanding commitment to the open-source community. Your contributions and the impact they have had on the community are highly commendable. I am new to the concept of identity and multi-tenancy, and my knowledge in this area is poor. Here is my use case: I have two separate apps, app1 and app2, each with its own authentication flow and email domain (app1mail.com and app2mail.com). User1 registers separately in both apps. Now, I want to integrate them into a single realm with a unified registration process. I have a few questions:

  1.  Is it possible for app1 and app2 to have separate authentication flows (e.g., app1 using 2FA and app2 using Email/Password)?
   2. Can welcome emails, forgot password emails, and other notifications be sent from different email addresses (e.g., [support@app1mail.com] for app1 and [support@app2mail.com] for app2)?
  3.  Can app1 and app2 have distinct login interfaces and styles?
  4.  If not, and I'm willing to compromise on points 1 and 2, please correct me on the following scenario:
   When User1 visits app1's website and registers, they are enrolled in the organization "clientapp1." If User1 tries to register in app2, it will fail, and instead, app2 will provide a link to join the organization "clientapp2." User1 must follow the link and successfully join "clientapp2." Now, my question is, what is the Identity Provider (IdP) for the organization, and what is the domain? I understand that when the email domain matches, users are automatically redirected to a specific organization. However, users of app1 and app2 may not necessarily have the same email domain. It's possible that I am asking the wrong question.
  5. Could you provide a sample code for a backend API that validates a user's role organization based on the token?

Thanks
Suman

**Comment by xgp** [comment]
@sumandas15 thanks for the detailed explanation. From your use cases, it sounds like you just need separate Realms in Keycloak. If your desire is to separate users, registrations, auth flows, themes, etc. it's best to just have separate realms. This extension is for use cases where the users are in the same Realm and the use case is to create logical groupings of users that can use a different IdP to log in.
