### ISSUE TITLE
Organization API improvement

### ISSUE THREAD

**Issue by grinay** [p2-inc/keycloak-orgs#94]
Hi Guys. I have just updated the organization plugin. A while ago I reported about an issue with pagination. Thanks for fixing it. Now it works. 
Wanted to ask you about some improvements there. 
There are two fields Name and Display name. As we have a case when names are not uniq for some reasons, we are using GUID instated of name and Put real organisation name into Display name. 
The search functionality seems only looking into Name filed. If it possible to add search on DisplayName field too. 
Thanks in advance.

**Comment by xgp** [comment]
> we have a case when names are not uniq

`name` has a unique contstraint. This should not be possible. How are you doing that @grinay ?

> add search on DisplayName field too

Should be easy. Just need to change these two queries:
- https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/model/jpa/entity/OrganizationEntity.java#L23
- https://github.com/p2-inc/keycloak-orgs/blob/main/src/main/java/io/phasetwo/service/model/jpa/entity/OrganizationEntity.java#L27

**Comment by grinay** [comment]
@xgp , yes you're right, this is not possible as Name field has uniq constraint. And because of that we use uniq guid on this field from db, and real company name put into DisplayName.

**Comment by xgp** [comment]
This was added in #95
