### ISSUE TITLE
Organization Id is not assigning as expected with API

### ISSUE THREAD

**Issue by syama-aot** [p2-inc/keycloak-orgs#96]
const axios = require("axios");
let data = JSON.stringify({
  id: "648aa11a7cee8d3fd5b7b183",
  name: "Testing",
  displayName: "Testing",
  realm: "cosmogence",
  attributes: {},
})

https://app.phasetwo.io/auth/realms/:realm/orgs API used for creation of new organization . organization id is not same as i passed in args . Its different b23d4b86-40c2-43cf-8bb5-b98ecaea5dd3. How can i get passed id value

**Comment by xgp** [comment]
`id` is a generated value. Anything you pass in will be ignored. You can retrieve the generated `id` value from the `Location` header in the response.
